# Default example config

api-backend:
  access_token:
    lifetime_seconds: 3600
    algorithm: HS256

  api:
    prefix: "/api"
    v2:
      prefix: "/v2"
      users: "/users"

  db:
    host: localhost
    port: 5432
    name: dbname
    echo: false
    echo_pool: false

  log:
    mode: info

  rabbit:
    host: localhost
    port: 5672
    vhostname: vhost
    secure: true

  run:
    dev_mode: false

  uvicorn:
    host: 127.0.0.1
    port: 8000
    workers: 1
    unix_socket: false

  s3:
    endpoint_url:
    bucket_name:

  secrets:
    session_secret:

  tg:
    widget_bot_id: 123456
